//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.225
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.EDICode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edicode.vips.gr.jp/SeikaCodePublish", ConfigurationName="EDICode.SeikaCodePublishSoap")]
    public interface SeikaCodePublishSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://edicode.vips.gr.jp/SeikaCodePublish/GetCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetCategory(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://edicode.vips.gr.jp/SeikaCodePublish/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetData(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeikaCodePublishSoapChannel : WebRole1.EDICode.SeikaCodePublishSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeikaCodePublishSoapClient : System.ServiceModel.ClientBase<WebRole1.EDICode.SeikaCodePublishSoap>, WebRole1.EDICode.SeikaCodePublishSoap {
        
        public SeikaCodePublishSoapClient() {
        }
        
        public SeikaCodePublishSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeikaCodePublishSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeikaCodePublishSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeikaCodePublishSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetCategory(string Name) {
            return base.Channel.GetCategory(Name);
        }
        
        public System.Xml.XmlNode GetData(string Name) {
            return base.Channel.GetData(Name);
        }
    }
}
